server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      routes:
        - id: usuarios-service
          uri: http://localhost:8082
          predicates:
            - Path=/usuario/**,/usuario/tipo/**,/sesion/**
        - id: usuarios-service-docs
          uri: http://localhost:8082
          predicates:
                - Path=/api/v1/service/v3/api-docs

        - id: reservas-service
          uri: http://localhost:8083
          predicates:
            - Path=/reservas,/reservas/**,/fotografos,/fotografos/**,/tipos-sesion,/tipos-sesion/**

        - id: pagos-service
          uri: http://localhost:8084
          predicates:
            - Path=/pagos,/pagos/**

        - id: evento-service
          uri: http://localhost:8085
          predicates:
            - Path=/eventos,/eventos/**
        - id: evento-service-docs
          uri: http://localhost:8085
          predicates:
              - Path=/api/v1/evento/v3/api-docs

        - id: notificaciones-service
          uri: http://localhost:8086
          predicates:
            - Path=/notificaciones,/notificaciones/**
        - id: service-notificaciones-docs
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/notificaciones/v3/api-docs
          
        - id: serice-resenas
          uri: http://localhost:8088
          predicates:
           - Path=/resenas,/resenas/**
        - id: serice-resenas-docs
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/resenas/v3/api-docs
        - id: contacto-service
          uri: http://localhost:8089
          predicates:
            - Path=/contacto,/contacto/**
        

        # Swagger docs Contacto
        - id: contacto-docs
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/contacto/v3/api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Servicio Usuarios
        url: /api/v1/service/v3/api-docs
      - name: Servicio Evento
        url: /api/v1/evento/v3/api-docs
      - name: Servicio Notificaciones
        url: /api/v1/notificaciones/v3/api-docs
      - name: Servicio Contacto
        url: /api/v1/contacto/v3/api-docs
      - name: Servicio Reseñas
        url: /api/v1/resenas/v3/api-docs