spring.application.name=service
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/db_akatellme?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/api/v1/service/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
