spring.application.name=service-auth
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/db_seguridad
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update


jwt.secret=493358340235739058340598340598340598340598340598


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


