spring.application.name=service-galeria
server.port=8089

spring.datasource.url=jdbc:mysql://localhost:3306/db_galeria?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Ruta donde se generará el JSON de la documentación
springdoc.api-docs.path=/galerias/v3/api-docs
# Título de la documentación
springdoc.swagger-ui.path=/swagger-ui.html
