spring.application.name=service
server.port=8086
spring.datasource.url=jdbc:mysql://localhost:3306/db_notificaciones?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=X
springdoc.swagger-ui.path=/swagger-ui.html