spring.application.name=contacto
server.port= 8089

spring.datasource.url=jdbc:mysql://localhost:3306/db_contacto?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

